# Generated by Django 5.0.4 on 2024-09-03 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('data', models.DateField()),
                ('observacao', models.TextField()),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('CON', 'Confirmado'), ('FIN', 'Concluído')], default='PEN', help_text='Estado atual do serviço', max_length=3, verbose_name='Status do Serviço')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
