# Generated by Django 5.0.4 on 2024-09-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('CNPJ', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
