# Generated by Django 5.0.4 on 2024-09-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0002_salao_proprietario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salao',
            name='proprietario_id',
        ),
    ]
