# Generated by Django 5.0.4 on 2024-09-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0002_salao_proprietario_salao_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salao',
            name='url_image',
            field=models.ImageField(blank=True, default='salao/default-salon.jpeg', null=True, upload_to='salao/'),
        ),
    ]
