# Generated by Django 5.0.4 on 2024-09-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0003_alter_salao_url_image'),
        ('salao', '0003_remove_salao_proprietario_id'),
    ]

    operations = [
    ]
