<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-09-02 17:52
=======
# Generated by Django 5.0.4 on 2024-09-02 17:06
>>>>>>> 6239d8e611d9b1012580cb90dac05ac2a8cb788b

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('salao', '0002_salao_proprietario_id'),
=======
        ('salao', '0001_initial'),
>>>>>>> 6239d8e611d9b1012580cb90dac05ac2a8cb788b
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao', models.DurationField()),
                ('salao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salao.salao')),
            ],
        ),
    ]
