# Generated by Django 5.0.4 on 2024-09-01 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('quantidade_estoque', models.IntegerField()),
                ('url_image', models.CharField(max_length=250)),
                ('salao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salao.salao')),
            ],
        ),
    ]
