# Generated by Django 5.0.4 on 2024-09-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='url_image',
            field=models.ImageField(blank=True, null=True, upload_to='produto/'),
        ),
    ]
